import { Weiweb3SDK } from "../sdk";
import { Network } from "../types/index";
import { getPayer } from "./local-config";
import { KeypairSigner } from "@metaplex-foundation/js";
import { Weiweb3Storage } from "@weiweb3/storage";

/**
 * Create an SDK instance using the local configuration generated by the Solana CLI
 *
 * @example
 * ```jsx
 * import { createWeiweb3SDK } from "@weiweb3/sdk/solana";
 *
 * // Select the network to create the SDK on
 * const sdk = createWeiweb3SDK("devnet");
 * ```
 *
 * @public
 */
export function createWeiweb3SDK(
  network: Network,
  storage: Weiweb3Storage = new Weiweb3Storage(),
): Weiweb3SDK {
  const payer = getPayer();
  const signer: KeypairSigner = {
    publicKey: payer.publicKey,
    secretKey: payer.secretKey,
  };
  const sdk = Weiweb3SDK.fromNetwork(network, storage);
  sdk.wallet.connect(signer);
  return sdk;
}
